Set
najibullahjafari/rails_react_webpack pull request #1
Opened 2023-11-08 23:59 UTC by najibullahjafari

Here I did the following requirements:

- Create a new Rails app.
- Use the command rails new -j webpack 
- Verify that the jsbundling-rails gem is added to your Gemfile.
- Initialize your project with Git.
- Install needed node dependencies as described in the previous lesson's tutorial.
- Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- Update webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- Create a static view that will be the root of your app.
- Create the App component with react-router and render it in your static view.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your Greeting component.

2023-11-09 00:43 UTC, AmaduKamara requested changes
# Status: Requires Changes ♻️ ♻️ ♻️

Hi @najibullahjafari,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 
✅ The Linter checks passed successfully 
✅ You used the `jsbundling-rails` gem as required and Babel and Webpack are configured correctly 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add the missing packages being used in your codebase in your package.json file. `axios`, `react-router-dom`. Kindly add those 👍🏽
- [ ] According to the project requirement, you're required to use redux for state management but redux is not being used as required. Kindly install redux and configure the store and actions as required. 👍🏽

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-09 00:43 UTC, AmaduKamara commented on README.md
> +- [📖 BudgetPro ](#ruby-on-rails-group-project)
- [ ] Kindly modify the title of this project as you're actually not working on the Budget App in this PR. Please edit in all areas you mentioned contents about the Budget App to Hello World with Rails React as that's what you're actually working on. 👍🏽

2023-11-09 00:43 UTC, AmaduKamara commented on README.md
> +
- [ ] Kindly modify the title of this project as you're actually not working on the Budget App in this PR. Please edit in all areas you mentioned contents about the Budget App to Hello World with Rails React as that's what you're actually working on. 👍🏽

2023-11-09 00:43 UTC, AmaduKamara commented on README.md
> +```
- [ ] Kindly modify the title of this project as you're actually not working on the Budget App in this PR. Please edit in all areas you mentioned contents about the Budget App to Hello World with Rails React as that's what you're actually working on. 👍🏽

2023-11-09 00:43 UTC, AmaduKamara commented on README.md
> +```
- [ ] Kindly modify the title of this project as you're actually not working on the Budget App in this PR. Please edit in all areas you mentioned contents about the Budget App to Hello World with Rails React as that's what you're actually working on. 👍🏽

2023-11-09 00:43 UTC, AmaduKamara commented on app/javascript/components/Greeting.js
> +  }, []);
- [ ] When I ran the app, it failed to load up successfully due to missing packages being used in your codebase but not in the package.json file, `axios` is not installed. Kindly fix that. 👍🏽

2023-11-09 00:43 UTC, AmaduKamara commented on app/javascript/application.js
> +};
- [ ] When I ran the app, it failed to load up successfully due to missing packages being used in your codebase but not in the package.json file, `react-router-dom` is not installed. Kindly fix that. 👍🏽

2023-11-10 16:16 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @najibullahjafari, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Requested dependencies have been installed :+1: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 16:16 UTC, FrederickMih commented on app/javascript/redux/greetings/greetingsSlice.js
> +  const response = await axios.get('http://127.0.0.1:3000//greetings/random');
- [Optional] It is a good practice to make our URL looks like an API(Ex. http://localhost:3000/api/v1) since we will be building APIs in the future using Rails :+1:

2023-11-10 16:16 UTC, FrederickMih commented on app/javascript/redux/greetings/greetingsSlice.js
> +  const response = await axios.get('http://127.0.0.1:3000//greetings/random');
- [ ] As you can see on the screenshot below, your two apps are not still successfully connecting together. No random greetings are displayed. Let's kindly fix the issue and submit once more for review.
![Screenshot from 2023-11-10 17-10-54](https://github.com/najibullahjafari/rails_react_webpack/assets/63087491/c8a4104d-63be-458c-a070-fa13ff6de341)

2023-11-10 16:26 UTC, najibullahjafari commented on app/javascript/redux/greetings/greetingsSlice.js
> +  const response = await axios.get('http://127.0.0.1:3000//greetings/random');
@FrederickMih 
In my machine it is working and displaying greetings. Did you runned seed?

2023-11-10 22:45 UTC, najibullahjafari commented on app/javascript/redux/greetings/greetingsSlice.js
> +  const response = await axios.get('http://127.0.0.1:3000//greetings/random');
@FrederickMih It is working well without any issue!

2023-11-10 23:47 UTC, Reem-lab approved these changes
# Hi @najibullahjafari,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  No Linters error 🚀
- [ ]  Followed GitFlow 💯
- [ ]  Great job working on the API and frontend side✨
- [ ]  Descriptive PR 💯
- [ ]  Messages are displayed well 🚀


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-11 11:29 UTC, merged